#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";

const docsDirArg = process.argv[2] || "docs";
const wikiDirArg = process.argv[3] || ".wiki";
const docsDir = path.resolve(docsDirArg);
const wikiDir = path.resolve(wikiDirArg);
const GENERATED_MARKER = "<!-- WEBRADIO-WIKI-GENERATED -->";

if (!fs.existsSync(docsDir) || !fs.statSync(docsDir).isDirectory()) {
  throw new Error("Documentation directory not found: " + docsDir);
}

fs.mkdirSync(wikiDir, { recursive: true });

function walk(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) files.push(...walk(full));
    else if (entry.isFile() && entry.name.toLowerCase().endsWith(".md")) files.push(full);
  }
  return files.sort((a, b) => a.localeCompare(b));
}

function removeGeneratedContent(dir) {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.name === ".git") continue;
    if (entry.isDirectory()) {
      removeGeneratedContent(full);
      if (fs.readdirSync(full).length === 0) fs.rmdirSync(full);
      continue;
    }
    const content = fs.readFileSync(full, "utf8");
    if (entry.name === "Home.md" || entry.name === "_Sidebar.md" || content.includes(GENERATED_MARKER)) {
      fs.rmSync(full, { force: true });
    }
  }
}

function titleFromMarkdown(content, fallback) {
  const match = content.match(/^#\\s+(.+)$/m);
  return match && match[1] ? match[1].trim() : fallback;
}

function wikiRelativePath(source) {
  return path.relative(docsDir, source).split(path.sep).join("/");
}

function normalizeTitle(filename) {
  return filename
    .replace(/\\.md$/i, "")
    .replace(/[-_]+/g, " ")
    .replace(/\\b\\w/g, function(c) { return c.toUpperCase(); });
}

function writeWikiPage(source) {
  const relative = wikiRelativePath(source);
  const target = path.join(wikiDir, relative);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  const content = fs.readFileSync(source, "utf8");
  const title = titleFromMarkdown(content, normalizeTitle(path.basename(relative)));
  fs.writeFileSync(target, GENERATED_MARKER + "\\n\\n" + content.trimEnd() + "\\n", "utf8");
  return { relative, title };
}

removeGeneratedContent(wikiDir);

const pages = walk(docsDir).map(writeWikiPage);
const rootPages = pages.filter(function(page) { return !page.relative.includes("/"); });
const groups = new Map();

for (const page of pages) {
  const parts = page.relative.split("/");
  if (parts.length === 1) continue;
  const group = parts[0];
  if (!groups.has(group)) groups.set(group, []);
  groups.get(group).push(page);
}

const homeLines = [
  GENERATED_MARKER,
  "",
  "# WebRadio Documentation",
  "",
  "This wiki is automatically synchronized from the docs/ directory of the WebRadio repository.",
  "",
  "> Source of truth: docs/ in the main repository. Edit the repository documentation instead of generated wiki pages.",
  "",
  "## Documentation",
  ""
];

for (const page of rootPages) {
  const filename = path.basename(page.relative);
  const wikiName = filename.toLowerCase() === "readme.md" ? "Readme" : filename.replace(/\\.md$/i, "");
  homeLines.push("- [" + page.title + "](" + wikiName + ")");
}

for (const [group, groupPages] of groups) {
  homeLines.push("", "## " + normalizeTitle(group), "");
  for (const page of groupPages) {
    homeLines.push("- [" + page.title + "](" + page.relative.replace(/\\.md$/i, "") + ")");
  }
}

homeLines.push(
  "",
  "## Repository",
  "",
  "- [WebRadio source repository](https://github.com/YourEliteSystems/WebRadio)",
  "- [Issues](https://github.com/YourEliteSystems/WebRadio/issues)",
  "- [Releases](https://github.com/YourEliteSystems/WebRadio/releases)",
  "",
  "Last generated by GitHub Actions from commit " + (process.env.GITHUB_SHA || "local") + ".",
  ""
);

fs.writeFileSync(path.join(wikiDir, "Home.md"), homeLines.join("\\n"), "utf8");

const sidebar = [GENERATED_MARKER, "", "### WebRadio", "", "- [Home](Home)", ""];

for (const page of rootPages) {
  const filename = path.basename(page.relative);
  if (filename.toLowerCase() === "readme.md") continue;
  sidebar.push("- [" + page.title + "](" + filename.replace(/\\.md$/i, "") + ")");
}

for (const [group, groupPages] of groups) {
  sidebar.push("", "### " + normalizeTitle(group), "");
  for (const page of groupPages) {
    sidebar.push("- [" + page.title + "](" + page.relative.replace(/\\.md$/i, "") + ")");
  }
}

fs.writeFileSync(path.join(wikiDir, "_Sidebar.md"), sidebar.join("\\n") + "\\n", "utf8");
console.log("Synchronized " + pages.length + " documentation pages into " + wikiDir);
