name: Build WebRadio

on:
  push:
    tags:
      - "v*"

jobs:

  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:

      - name: Repository klonen
        uses: actions/checkout@v4

      - name: Node installieren
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Dependencies installieren
        run: npm install

      - name: App bauen
        run: npm run make

      - name: Release erstellen
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/make/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}